In [19]:
import seaborn as sns
import pandas as pd

In [20]:
df = pd.read_csv("/home/nijesh-shrestha/Downloads/Advertising.csv")
df.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [21]:
df.shape

(200, 5)

In [22]:
df.drop(df.columns[0], axis=1, inplace=True)
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [23]:
df.shape

(200, 4)

In [24]:
df.TV.corr(df.sales)

np.float64(0.7822244248616061)

In [ ]:
from sklearn.linear_model import LinearRegression

feature_cols = ['TV', 'radio', 'newspaper']
X = df[feature_cols]
y = df.sales

lml = LinearRegression()
lml.fit(X, y)

print(lml.intercept_)
print(lml.coef_)

2.938889369459412
[ 0.04576465  0.18853002 -0.00103749]

In [ ]:
list(zip(feature_cols, lml.coef_))

[('TV', np.float64(0.0457646454553976)),
 ('radio', np.float64(0.18853001691820448)),
 ('newspaper', np.float64(-0.0010374930424763285))]

In [ ]:
lml_preds = lml.predict(X[['TV', 'radio', 'newspaper']])

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

print("R2S :", r2_score(y, lml_preds))
print("MSE :", mean_squared_error(y, lml_preds))

R2S : 0.8972106381789522
MSE : 2.784126314510936