In [360]:
import pandas as pd

In [361]:
data = {
    "name": ["Bill", "Tom", "Tim", "John", "Alex", "Vanessa", "Kate"],
    "score": [90, 80, 85, 75, 95, 60, 65],
    "sport": ["Wrestling", "Football", "Skiing", "Swimming", "Tennis", "Karate", "Surfing"],
    "gender": ["M", "M", "M", "M", "F","F", "F"]
}

df = pd.DataFrame(data)
df

      name  score      sport gender
0     Bill     90  Wrestling      M
1      Tom     80   Football      M
2      Tim     85     Skiing      M
3     John     75   Swimming      M
4     Alex     95     Tennis      F
5  Vanessa     60     Karate      F
6     Kate     65    Surfing      F

In [362]:
interested_col_df = df[["name", "score", "sport"]]
interested_col_df

      name  score      sport
0     Bill     90  Wrestling
1      Tom     80   Football
2      Tim     85     Skiing
3     John     75   Swimming
4     Alex     95     Tennis
5  Vanessa     60     Karate
6     Kate     65    Surfing

In [363]:
df.head(5)

   name  score      sport gender
0  Bill     90  Wrestling      M
1   Tom     80   Football      M
2   Tim     85     Skiing      M
3  John     75   Swimming      M
4  Alex     95     Tennis      F

In [364]:
df.tail(5)

      name  score     sport gender
2      Tim     85    Skiing      M
3     John     75  Swimming      M
4     Alex     95    Tennis      F
5  Vanessa     60    Karate      F
6     Kate     65   Surfing      F

In [365]:
df.sample(n=3, random_state=42)

      name  score      sport gender
0     Bill     90  Wrestling      M
1      Tom     80   Football      M
5  Vanessa     60     Karate      F

In [366]:
df.describe()

           score
count   7.000000
mean   78.571429
std    12.817399
min    60.000000
25%    70.000000
50%    80.000000
75%    87.500000
max    95.000000

In [367]:
df.columns

Index(['name', 'score', 'sport', 'gender'], dtype='object')

In [368]:
print(df.loc[2])
print("-------------------------")
print(df.iloc[1:4, 0:2])

name         Tim
score         85
sport     Skiing
gender         M
Name: 2, dtype: object
-------------------------
   name  score
1   Tom     80
2   Tim     85
3  John     75

In [369]:
df.set_index("name", inplace=True)
df

         score      sport gender
name
Bill        90  Wrestling      M
Tom         80   Football      M
Tim         85     Skiing      M
John        75   Swimming      M
Alex        95     Tennis      F
Vanessa     60     Karate      F
Kate        65    Surfing      F

In [370]:
df.reset_index(inplace=True)
df

      name  score      sport gender
0     Bill     90  Wrestling      M
1      Tom     80   Football      M
2      Tim     85     Skiing      M
3     John     75   Swimming      M
4     Alex     95     Tennis      F
5  Vanessa     60     Karate      F
6     Kate     65    Surfing      F

In [371]:
df.set_index("name", inplace=True)

In [372]:
print(df.loc["Bill"])
print("-----------------------")
print(df.iloc[1, 2])
print("-----------------------")
print(df.iloc[1, [0, 2]])

score            90
sport     Wrestling
gender            M
Name: Bill, dtype: object
-----------------------
M
-----------------------
score     80
gender     M
Name: Tom, dtype: object

In [373]:
print(df.loc["Bill": "Tom", "score": "gender"])
print("---------iloc------------")
print(df.iloc[1:3, 0:2])

      score      sport gender
name
Bill     90  Wrestling      M
Tom      80   Football      M
---------iloc------------
      score     sport
name
Tom      80  Football
Tim      85    Skiing

In [374]:
print(df["gender"] == "M")
df[df["gender"] == "M"]

name
Bill        True
Tom         True
Tim         True
John        True
Alex       False
Vanessa    False
Kate       False
Name: gender, dtype: bool

      score      sport gender
name
Bill     90  Wrestling      M
Tom      80   Football      M
Tim      85     Skiing      M
John     75   Swimming      M

In [375]:
print(df[(df["score"] > 80) & (df["gender"] == "M")])
print("-----------------------")
print(df[((df["sport"] > "Wrestling") | (df["sport"] == "Swimming")) & (df["score"] > 70)])

      score      sport gender
name
Bill     90  Wrestling      M
Tim      85     Skiing      M
-----------------------
      score     sport gender
name
John     75  Swimming      M

In [376]:
print(df.sort_values("score", ascending=False))

         score      sport gender
name
Alex        95     Tennis      F
Bill        90  Wrestling      M
Tim         85     Skiing      M
Tom         80   Football      M
John        75   Swimming      M
Kate        65    Surfing      F
Vanessa     60     Karate      F

In [377]:
print(df.sort_values(["gender", "score"], ascending=[True, False]))

         score      sport gender
name
Alex        95     Tennis      F
Kate        65    Surfing      F
Vanessa     60     Karate      F
Bill        90  Wrestling      M
Tim         85     Skiing      M
Tom         80   Football      M
John        75   Swimming      M