In [39]:
import pandas as pd

In [40]:
df = pd.read_csv("datasets/datasets/data.txt", sep="\t")
df

  name  score gender
0  Tim     80      M
1  Tom     85      M
2  Kim     70      F
3  Sam     90      M
4  Efe     75      M

In [41]:
df2 = pd.read_csv(r"D:\mlWithGenAi\pandas\datasets\datasets\data.txt", sep="\t")
df2

  name  score gender
0  Tim     80      M
1  Tom     85      M
2  Kim     70      F
3  Sam     90      M
4  Efe     75      M